testObject:
  name: "Server 0815"
  testObjectType: "IntermediaerServer" # one of (IntermediaerServer, KimFachdienst, VsdmFachdienst, VpnKonzentrator, VpnRegServer, IdpFachdienst, IdpEgkFachdienst)
  ipAddressOrFqdn: "127.0.0.1"
  port: 8443
  ocspGracePeriodSeconds: 0
  tslDownloadIntervalSeconds: 2
  tslProcessingTimeSeconds: 3

ocspResponder:
  ipAddressOrFqdn: "127.0.0.1"
  port: 8083

tslProvider:
  ipAddressOrFqdn: "127.0.0.1"
  port: 8084
