tlsSettings:
    socketTimeoutMsec: 15000
    enabledProtocols:
        - TLSv1.2
    #            - TLSv1.3
    ecCiphersSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    rsaCiphersSuites:
        - TLS_DHE_RSA_WITH_AES_256_CBC_SHA
        - TLS_DHE_RSA_WITH_AES_128_CBC_SHA
